# Generated by Django 4.0 on 2022-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_bio_alter_profile_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
