# Generated by Django 4.0 on 2022-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_experience_e_from_remove_experience_e_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='s_level',
            field=models.CharField(default='', max_length=255),
        ),
    ]
